import React from 'react'
import Head from 'next/head'

const SEO = () => {
    return (
        <div>
          <Head>
           <title>Globe 3d map</title>
           <meta name="description" content="Generated by Bruno Soares" />
           <link rel="icon" href="/favicon.ico" />
        </Head>
        </div>
    )
}

export default SEO
